### ISSUE TITLE
Line 25 type, additional character '2' 

### ISSUE THREAD

**Issue by saqib-s** [SeeSmitty/Powershell#1]
Line 25

Currently is: 

Add-AzureADGroupMember -ObjectId $GroupObjectID**2**.ObjectID -RefObjectId $y2.ObjectId -InformationAction SilentlyContinue

the 2 needs to be removed. 

Add-AzureADGroupMember -ObjectId **$GroupObjectID**.ObjectID -RefObjectId $y2.ObjectId -InformationAction SilentlyContinue

**Comment by SeeSmitty** [comment]
Great catch! Updated. Thanks
