### ISSUE TITLE
'ManagedBy' not being set in Set-DistributionGroupDetails

### ISSUE THREAD

**Issue by jlavetan** [SeeSmitty/Powershell#3]
Is there a specific reason the "ManagedBy' parameter isn't set? I noticed it's missing from the Set-DistributionGroupDetails script.

**Comment by SeeSmitty** [comment]
Excellent catch. I think when I switched from version one to version two, I intended to move it from the 'New-GroupCreation' section to 'Set-GroupProperties' section. The Default for 'Set-DistributionGroup' defaults to the user account that is running the command, so it didn't error in my testing, and I just missed it. 

I updated the script to include that section, thanks for the assist. Let me know if that doesn't resolve the issue for you.
