### ISSUE TITLE
Set-DistributionGroupsBulk.ps1 completely useless.

### ISSUE THREAD

**Issue by brolifen** [SeeSmitty/Powershell#5]
The spirit of the script is respectable but a lot of it seems like it's just a placeholder. Most attribute are not written especially the types that are booleans or a list of users for instance for the moderated attribute.

Still needs a lot of work and testing.

**Comment by SeeSmitty** [comment]
I appreciate the thoughts. I will definitely revisit this, and review the suggested edits. I agree many things are null or empty, but the intent there is that I was trying to make this flexible to work for different environments where some organizations use things that mine does not. I didn't need every field there, but I assumed anyone using it could remove anything they knew for sure they didn't need.

I'll see if there are other ways I can optimize this a little better. I'd definitely appreciate specific ideas if you have them.
